Verbindung testen

In [2]:
import requests
import pandas as pd

In [23]:
# 1. API anpingen
url_weather = "https://archive-api.open-meteo.com/v1/archive?latitude=40.7143&longitude=-74.006&start_date=2023-01-01&end_date=2023-01-31&daily=temperature_2m_max,temperature_2m_min,precipitation_sum&timezone=America%2FNew_York"
response = requests.get(url_weather)

print(f"Status Code: {response.status_code}") # 200 bedeutet "Alles OK!"

Status Code: 200

Daten prüfen

In [25]:
# 2. Die rohen Daten als JSON / Python Dictionary
rohe_daten = response.json()

# 3. Wir laden es in einen DataFrame, schauen uns an, was die API uns gibt
wetter_tabelle = pd.DataFrame(rohe_daten['daily'])
display(wetter_tabelle.head(10))

         time  temperature_2m_max  temperature_2m_min  precipitation_sum
0  2023-01-01                11.9                 4.9                2.1
1  2023-01-02                12.9                 4.6                0.5
2  2023-01-03                12.9                 6.3                9.5
3  2023-01-04                18.0                 9.6                2.3
4  2023-01-05                13.1                 7.4                0.0
5  2023-01-06                 8.7                 3.3                9.6
6  2023-01-07                 8.2                 0.5                0.0
7  2023-01-08                 4.2                -2.3                0.0
8  2023-01-09                 7.2                 0.8                1.5
9  2023-01-10                 6.3                 0.1                0.0

Funktion ausprobieren

In [28]:
# 4. In eigene, Spaltennamen übersetzen!

weather_tabelle = pd.DataFrame({
    'date_key': rohe_daten['daily']['time'],                     
    'temp_max_celsius': rohe_daten['daily']['temperature_2m_max'],     
    'temp_min_celsius': rohe_daten['daily']['temperature_2m_min'],
    'precipitation_mm': rohe_daten['daily']['precipitation_sum']        
})

display(weather_tabelle.head(10))

     date_key  temp_max_celsius  temp_min_celsius  precipitation_mm
0  2023-01-01              11.9               4.9               2.1
1  2023-01-02              12.9               4.6               0.5
2  2023-01-03              12.9               6.3               9.5
3  2023-01-04              18.0               9.6               2.3
4  2023-01-05              13.1               7.4               0.0
5  2023-01-06               8.7               3.3               9.6
6  2023-01-07               8.2               0.5               0.0
7  2023-01-08               4.2              -2.3               0.0
8  2023-01-09               7.2               0.8               1.5
9  2023-01-10               6.3               0.1               0.0

2. Testlauf mit einem Monat der Wetterdaten zur Verknüpfung mit den Testdaten von Citibike:

In [ ]:
import requests
import pandas as pd
from sqlalchemy import create_engine

# 1. Wir fragen das historische Wetter für Juli 2023 in New York / Jersey City ab
print("Hole historische Wetterdaten für Juli 2023...")
url = "https://archive-api.open-meteo.com/v1/archive?latitude=40.7143&longitude=-74.006&start_date=2023-07-01&end_date=2023-07-31&daily=temperature_2m_max,temperature_2m_min,precipitation_sum&timezone=America%2FNew_York"

response = requests.get(url)
data = response.json()

# 2. Wir bauen daraus unsere Python-Tabelle (DataFrame)
weather_df = pd.DataFrame({
    'date_key': data['daily']['time'], # Das Datum als Schlüssel für unser Star Schema (exakt wie bei den Citibike-Daten)
    'temp_max_celsius': data['daily']['temperature_2m_max'],
    'temp_min_celsius': data['daily']['temperature_2m_min'],
    'precipitation_mm': data['daily']['precipitation_sum']
})

print("\nVorschau der Wetterdaten:")
display(weather_df.head())

# 3. Wir laden die Daten direkt als Staging-Tabelle in die Datenbank
db_url = 'postgresql://admin:password123@localhost:5432/citibike_dwh'
engine = create_engine(db_url)

try:
    weather_df.to_sql('staging_weather_historical', engine, if_exists='replace', index=False)
    print("\nErfolg! 31 Tage Wetterdaten wurden in 'staging_weather_historical' geladen.")
except Exception as e:
    print(f"\nFehler beim Schreiben in die Datenbank: {e}")

Hole historische Wetterdaten für Juli 2023...

Vorschau der Wetterdaten:

     date_key  temp_max_celsius  temp_min_celsius  precipitation_mm
0  2023-07-01              26.9              17.7               0.1
1  2023-07-02              31.2              20.4              16.0
2  2023-07-03              31.1              22.4              17.8
3  2023-07-04              29.4              21.3               5.4
4  2023-07-05              32.3              21.0               0.0

Erfolg! 31 Tage Wetterdaten wurden in 'staging_weather_historical' geladen.